/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package darksouls3;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JFrame;
import javax.swing.*;

/**
 *
 * @author lleshi.alessandro
 */
public class FormChoiseEnding extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormChoiseEnding.class.getName());

    /**
     * Creates new form FormChoiseEnding
     */
    public FormChoiseEnding(GameManager g) {
        initComponents();
        JPanel mainPanel = new JPanel(new BorderLayout());
        JPanel buttonPanel = new JPanel(new GridLayout(1,3));
        JButton badEnd = new JButton("choose the darkness path");
        JButton classicEnd = new JButton("choose your path, your ideal");
        JButton goodEnd = new JButton("choose the best path for Lothric");
        
        buttonPanel.add(badEnd);
        buttonPanel.add(classicEnd);
        buttonPanel.add(goodEnd);
        
        //da implementare i 3 bottoni, devo aggiungere il controllo degli npc e quinid se è possibile fare il finale, poi dovrò scegliere 3 immagini
        ActionListener actionBadEnd = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        };
        badEnd.addActionListener(actionBadEnd);
        
        
        ActionListener actionClassicEnd = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        };
        classicEnd.addActionListener(actionClassicEnd);
        
        
        ActionListener actionGoodEnd = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        };
        goodEnd.addActionListener(actionGoodEnd);
        
        
        mainPanel.add(buttonPanel, BorderLayout.CENTER);
        this.add(mainPanel);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormChoiseEnding(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
