/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package darksouls3;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author aless
 */
public class OpenGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OpenGame.class.getName());
    
    
    /**
     * Creates new form OpenGame
     */
    public OpenGame() {
        initComponents();
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());

        // Panel in NORTH con titolo
        JPanel northPanel = new JPanel(new BorderLayout());
        JLabel label1 = new JLabel("Titolo");
        label1.setFont(new Font("Arial", Font.BOLD, 24));
        label1.setHorizontalAlignment(SwingConstants.CENTER);  // centra orizzontalmente
        northPanel.add(label1, BorderLayout.CENTER);           // centra all’interno del panel
        northPanel.setPreferredSize(new Dimension(0, 80));    // altezza del nord
        mainPanel.add(northPanel, BorderLayout.NORTH);

        // Panel in WEST con bottone
        JPanel westPanel = new JPanel(new BorderLayout());     // layout per centrare il bottone
        JButton button = new JButton("New Game");
        westPanel.add(button, BorderLayout.CENTER);           // centro del panel a sinistra
        westPanel.setPreferredSize(new Dimension(120, 0));    // larghezza del panel
        mainPanel.add(westPanel, BorderLayout.WEST);

        // aggiungi il mainPanel al frame
        this.add(mainPanel);
        this.setSize(840, 420);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OpenGame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
